# Generated by Django 4.2.2 on 2023-07-23 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0004_alter_user_last_login'),
        ('channel', '0002_alter_membership_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel',
            old_name='owner_id',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='channel_id',
            new_name='channel',
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='userauth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='channel',
            name='members',
            field=models.ManyToManyField(default=None, related_name='followings', through='channel.Membership', to='userauth.user'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('normal', 'Normal'), ('vip', 'Vip')], default='normal', max_length=10),
        ),
    ]
