# Generated by Django 4.2.1 on 2023-07-19 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0002_alter_channel_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel',
            old_name='owner',
            new_name='owner_id',
        ),
    ]
