# Generated by Django 4.2.1 on 2023-07-19 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0003_rename_owner_channel_owner_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(max_length=10)),
                ('format', models.CharField(max_length=60)),
                ('type', models.CharField(max_length=60)),
                ('duration', models.IntegerField(max_length=30, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='channel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(max_length=30, null=True)),
                ('title', models.CharField(max_length=200, null=True)),
                ('summary', models.CharField(max_length=400, null=True)),
                ('content', models.CharField(max_length=1000)),
                ('media', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='channel.media')),
            ],
        ),
    ]
