# Generated by Django 4.2.2 on 2023-07-24 10:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0004_alter_user_last_login'),
        ('channel', '0005_alter_membership_role_alter_post_published_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='members',
            field=models.ManyToManyField(related_name='followings', through='channel.Membership', to='userauth.user'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('normal', 'Normal'), ('vip', 'Vip')], default='normal', max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='published_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 24, 10, 43, 23, 580530)),
        ),
    ]
