# Generated by Django 4.2.2 on 2023-07-29 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0007_alter_membership_role_alter_post_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='share',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('normal', 'Normal'), ('vip', 'Vip')], default='normal', max_length=10),
        ),
    ]
