# Generated by Django 4.2.2 on 2023-08-04 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0005_user_nickname_alter_user_username'),
        ('channel', '0009_alter_membership_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='share',
        ),
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('normal', 'Normal'), ('vip', 'Vip')], default='normal', max_length=10),
        ),
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='channel.channel')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userauth.user')),
            ],
        ),
    ]
