# Generated by Django 4.2.2 on 2023-08-21 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0013_purchasedpost'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tariff',
            new_name='Plan',
        ),
    ]
