# Generated by Django 4.2.1 on 2023-06-05 18:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_add_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 5, 18, 35, 46, 462583, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
